# Generated by Django 3.0.8 on 2020-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200807_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='item_count',
            field=models.CharField(max_length=64, verbose_name='상품수'),
        ),
    ]
