# Generated by Django 3.0.8 on 2020-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200812_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='orderstate',
            field=models.CharField(default='주문완료', max_length=64),
        ),
    ]
