# Generated by Django 3.1.2 on 2020-10-22 04:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20200809_1945'),
        ('users', '0004_buy_orderstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='check_YN',
            field=models.CharField(default='N', max_length=2, verbose_name='선택여부'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.CharField(max_length=64, verbose_name='상품수')),
                ('buy_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='구매날짜')),
                ('postcode', models.CharField(max_length=64, verbose_name='우편번호')),
                ('address', models.CharField(max_length=64, verbose_name='주소')),
                ('detail_address', models.CharField(max_length=64, verbose_name='상세주소')),
                ('phone', models.CharField(max_length=64, verbose_name='전화번호')),
                ('price', models.IntegerField(verbose_name='주문가격')),
                ('orderstate', models.CharField(default='주문완료', max_length=64)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sellers.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
