# Generated by Django 3.1.2 on 2020-10-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201022_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='총 가격'),
        ),
    ]
