# Generated by Django 3.1.2 on 2020-10-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buy_date',
            new_name='order_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderstate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(default='주문완료', max_length=64, verbose_name='주문상태'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='결제가격'),
        ),
    ]
