# Generated by Django 3.1.2 on 2020-10-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201023_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.IntegerField(default=0, verbose_name='주문번호'),
        ),
    ]
