# Generated by Django 3.1.2 on 2020-10-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='', max_length=64, verbose_name='받는 이'),
        ),
    ]
