# Generated by Django 3.1.2 on 2020-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_order_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Shipping_message',
            field=models.CharField(default='', max_length=64, verbose_name='배송메세지'),
        ),
    ]
