# Generated by Django 3.1.2 on 2020-10-28 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_order_shipping_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Shipping_message',
            new_name='shipping_message',
        ),
    ]
