# Generated by Django 3.1.2 on 2020-11-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20200809_1945'),
        ('users', '0011_auto_20201028_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellers.seller'),
        ),
    ]
