# Generated by Django 3.1.2 on 2020-11-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_order_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.CharField(default='', max_length=64, verbose_name='판매자명'),
        ),
    ]
