# Generated by Django 3.1.2 on 2020-11-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_order_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
    ]
