# Generated by Django 3.1.2 on 2020-11-02 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20200809_1945'),
        ('users', '0018_remove_order_seller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sellers.seller'),
        ),
    ]
