# Generated by Django 3.1.2 on 2020-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_order_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(default='', max_length=64, verbose_name='운송장번호'),
        ),
    ]
