# Generated by Django 3.1.2 on 2020-11-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(default='', max_length=64, verbose_name='지불방식'),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.CharField(default='', max_length=128, verbose_name='매출전표 url'),
        ),
    ]
