# Generated by Django 3.1.2 on 2020-11-05 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201104_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_code',
            field=models.IntegerField(default=0, verbose_name='주문번호'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='구매날짜'),
        ),
    ]
