# Generated by Django 2.2.14 on 2020-08-08 16:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.CharField(default=0, max_length=32, verbose_name='상품가격'),
        ),
    ]
