# Generated by Django 2.2.14 on 2020-08-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20200809_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='detail_image',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='대표사진'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=32, verbose_name='상품제목'),
        ),
    ]
