# Generated by Django 3.1.2 on 2020-11-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_auto_20200809_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shipping_fee',
            field=models.IntegerField(default=0, verbose_name='배송비'),
        ),
    ]
